// lib/services-data.ts — Fulgur Service
// Copia esatta da GEMINI.md sezione 3

export interface Service {
  id: string
  slug: string
  title: string
  shortDesc: string
  longDesc: string
  icon: string  // nome icona @phosphor-icons
  featured: boolean
  keywords: string[]
  benefits: string[]
  sectors: string[]  // a chi è rivolto
  metaTitle: string
  metaDescription: string
  image: string
}

export const SERVICES: Service[] = [
  {
    id: '01',
    slug: 'pulizie-aziendali',
    title: 'Pulizie Aziendali',
    shortDesc: 'Uffici, sedi operative e spazi commerciali sempre impeccabili.',
    longDesc: 'Garantiamo ambienti di lavoro puliti, igienici e professionali. Gestiamo pulizie ordinarie e straordinarie per uffici, sedi aziendali, showroom e spazi commerciali di qualsiasi dimensione. Team dedicato, prodotti eco-certificati, interventi programmati su misura.',
    icon: 'Buildings',
    featured: true,
    keywords: ['pulizie uffici Parma', 'pulizie aziendali Parma', 'pulizie commerciali Parma'],
    benefits: ['Pulizie ordinarie giornaliere/settimanali', 'Pulizie straordinarie a fondo', 'Sanificazione ambienti', 'Prodotti eco-sostenibili certificati', 'Team dedicato e formato'],
    sectors: ['Uffici direzionali', 'Open space', 'Showroom', 'Negozi', 'Banche e assicurazioni'],
    metaTitle: 'Pulizie Aziendali Parma | Uffici e Spazi Commerciali — Fulgur Service',
    metaDescription: 'Pulizie professionali per uffici, sedi aziendali e spazi commerciali a Parma. Team qualificato, prodotti eco-certificati, sopralluogo gratuito. Chiama ora.',
    image: '/images/servizi/pulizie-aziendali-parma.jpg',
  },
  {
    id: '02',
    slug: 'pulizie-industriali',
    title: 'Pulizie Industriali',
    shortDesc: 'Capannoni, magazzini e impianti produttivi: pulizia al livello industriale.',
    longDesc: 'Interventi specializzati per ambienti industriali: capannoni produttivi, magazzini logistici, impianti di produzione, aree di carico/scarico. Macchinari professionali ad alta prestazione, operatori formati per ambienti difficili.',
    icon: 'Factory',
    featured: true,
    keywords: ['pulizie industriali Parma', 'pulizie capannoni Parma', 'pulizie magazzini Parma'],
    benefits: ['Pulizia pavimenti industriali', 'Rimozione oli e grassi', 'Pulizia macchinari e linee', 'Smaltimento rifiuti industriali', 'Interventi in orari produzione ferma'],
    sectors: ['Capannoni produttivi', 'Magazzini logistici', 'Impianti alimentari', 'Officine meccaniche', 'Centri distribuzione'],
    metaTitle: 'Pulizie Industriali Parma | Capannoni e Magazzini — Fulgur Service',
    metaDescription: 'Pulizie industriali a Parma per capannoni, magazzini e impianti produttivi. Macchinari professionali, operatori specializzati. Preventivo gratuito.',
    image: '/images/servizi/pulizie-industriali-parma.jpg',
  },
  {
    id: '03',
    slug: 'settore-sanitario',
    title: 'Settore Sanitario',
    shortDesc: 'Protocolli HACCP, prodotti certificati, environments sempre sicuri.',
    longDesc: 'La pulizia in ambienti sanitari non è ordinaria amministrazione — è igiene clinica. Seguiamo protocolli certificati, usiamo prodotti virucidi e battericidi approvati, con operatori formati specificamente per ambienti ad alto rischio.',
    icon: 'FirstAidKit',
    featured: true,
    keywords: ['sanificazione Parma', 'pulizie sanitarie Parma', 'pulizie cliniche Parma', 'igienizzazione medica Parma'],
    benefits: ['Protocolli HACCP certificati', 'Prodotti virucidi e battericidi', 'Sanificazione ad ozono', 'Pulizia sale operatorie', 'Report interventi documentati'],
    sectors: ['Cliniche e poliambulatori', 'Studi medici', 'Dentisti e laboratori', 'Farmacie', 'Case di cura'],
    metaTitle: 'Sanificazione e Pulizie Sanitarie Parma | Cliniche e Studi — Fulgur Service',
    metaDescription: 'Sanificazione e pulizie professionali per strutture sanitarie a Parma. Protocolli HACCP, prodotti certificati, personale specializzato. Contattaci.',
    image: '/images/servizi/pulizie-palestre-strutture-sportive-parma.jpg',
  },
  {
    id: '04',
    slug: 'pulizie-condomini',
    title: 'Pulizie Condomini',
    shortDesc: 'Parti comuni, scale, androni e aree esterne: gestione completa.',
    longDesc: 'Gestiamo la pulizia di tutte le parti comuni condominiali: scale, androni, ascensori, garage, cantine, aree verdi e parcheggi. Contratti annuali con report mensili per gli amministratori. Rendicontazione digitale trasparente.',
    icon: 'BuildingApartment',
    featured: false,
    keywords: ['pulizie condomini Parma', 'pulizie scale condominio Parma', 'pulizie parti comuni Parma'],
    benefits: ['Pulizie scale e androni', 'Pulizia ascensori', 'Aree garage e cantine', 'Aree verdi esterne', 'Report per amministratori'],
    sectors: ['Condomini residenziali', 'Palazzi signorili', 'Complessi condominiali', 'Residence'],
    metaTitle: 'Pulizie Condomini Parma | Parti Comuni e Scale — Fulgur Service',
    metaDescription: 'Pulizie professionali per condomini a Parma. Scale, androni, garage, aree comuni. Contratti annuali, report digitali per amministratori. Sopralluogo gratuito.',
    image: '/images/servizi/pulizie-condomini-parma.jpg',
  },
  {
    id: '05',
    slug: 'settore-alberghiero',
    title: 'Settore Alberghiero',
    shortDesc: 'Hotel, B&B e strutture ricettive: standard da 5 stelle.',
    longDesc: "Nel settore alberghiero la pulizia è parte dell'esperienza degli ospiti. Gestiamo pulizia camere, spazi comuni, ristoranti, spa e aree esterne con la cura e la discrezione che il settore richiede. Interventi programmati in base alle esigenze operative.",
    icon: 'Bed',
    featured: false,
    keywords: ['pulizie hotel Parma', 'pulizie alberghi Parma', 'pulizie B&B Parma', 'pulizie structures ricettive Parma'],
    benefits: ['Pulizia camere e suite', 'Spazi comuni e lobby', 'Ristoranti e cucine', 'Spa e piscine', 'Aree esterne e parcheggi'],
    sectors: ['Hotel 3-5 stelle', 'B&B e affittacamere', 'Agriturismi', 'Residence turistici'],
    metaTitle: 'Pulizie Hotel e B&B Parma | Settore Alberghiero — Fulgur Service',
    metaDescription: 'Pulizie professionali per hotel, B&B e strutture ricettive a Parma. Standard alberghieri garantiti. Team discreto e affidabile. Preventivo gratuito.',
    image: '/images/servizi/pulizie-hotel-alberghi-parma.png',
  },
  {
    id: '06',
    slug: 'trattamento-superfici',
    title: 'Trattamento Superfici',
    shortDesc: 'Gres, marmo, parquet, cotto, resina: protezione e valorizzazione.',
    longDesc: 'Non solo pulizia — trattiamo le superfici per proteggerle e valorizzarle nel tempo. Cristallizzazione e lucidatura marmo, trattamento e impregnazione gres porcellanato, oliatura e lucidatura parquet, trattamento cotto e resina, pulizia e sanificazione moquette.',
    icon: 'Sparkle',
    featured: true,
    keywords: ['trattamento superfici Parma', 'lucidatura pavimenti Parma', 'cristallizzazione marmo Parma', 'trattamento gres Parma'],
    benefits: ['Cristallizzazione marmo', 'Trattamento gres e gres porcellanato', 'Oliatura parquet', 'Trattamento cotto', 'Pulizia resina e moquette'],
    sectors: ['Abitazioni private', 'Uffici rappresentanza', 'Negozi e showroom', 'Hotel di lusso', 'Musei e gallerie'],
    metaTitle: 'Trattamento Superfici Parma | Marmo, Parquet, Gres — Fulgur Service',
    metaDescription: 'Trattamento professionale superfici a Parma: marmo, parquet, gres, cotto, resina. Cristallizzazione, lucidatura, protezione. Sopralluogo gratuito.',
    image: '/images/trattamento-superfici-parma.jpg',
  },
  {
    id: '07',
    slug: 'pulizie-fine-cantiere',
    title: 'Fine Cantiere',
    shortDesc: 'Post-costruzione e ristrutturazione: consegni uno spazio impeccabile.',
    longDesc: 'Le pulizie di fine cantiere richiedono esperienza e attrezzatura specifica: rimozione calce, cemento, vernice, residui di lavorazione, polveri edili. Interveniamo su nuove costruzioni, ristrutturazioni complete e parziali. Il risultato è uno spazio pronto alla consegna.',
    icon: 'HardHat',
    featured: false,
    keywords: ['pulizie fine cantiere Parma', 'pulizie post cantiere Parma', 'pulizie post ristrutturazione Parma'],
    benefits: ['Rimozione calce e cemento', 'Pulizia vetri da residui', 'Aspirazione polveri edili', 'Lucidatura pavimenti nuovi', 'Sgombero rifiuti edili'],
    sectors: ['Nuove costruzioni', 'Ristrutturazioni complete', 'Appartamenti da vendere', 'Locali commerciali nuovi'],
    metaTitle: 'Pulizie Fine Cantiere Parma | Post Costruzione — Fulgur Service',
    metaDescription: 'Pulizie di fine cantiere a Parma per nuove costruzioni e ristrutturazioni. Rimozione calce, cemento, polveri edili. Consegna impeccabile garantita.',
    image: '/images/servizi/pulizie-fine-cantiere-parma.jpg',
  },
  {
    id: '08',
    slug: 'vetrate-altezza',
    title: 'Vetrate in Altezza',
    shortDesc: 'Facciate vetrate, finestre e lucernari: pulizia in quota in sicurezza.',
    longDesc: 'La pulizia di vetrate e facciate in altezza richiede attrezzatura specialistica e operatori certificati per il lavoro in quota. Gestiamo finestre alte, facciate vetrate di edifici commerciali e industriali, lucernari e cupole con sistemi di sicurezza certificati.',
    icon: 'ArrowsOutSimple',
    featured: false,
    keywords: ['pulizia vetrate altezza Parma', 'lavaggio vetri altezza Parma', 'pulizia facciate vetrate Parma'],
    benefits: ['Operatori certificati lavoro in quota', 'Funi e piattaforme certificate', 'Facciate vetrate edifici', 'Lucernari e cupole', 'Finestre industriali'],
    sectors: ['Palazzi direzionali', 'Centri commerciali', 'Edifici industriali', 'Strutture pubbliche'],
    metaTitle: 'Pulizia Vetrate in Altezza Parma | Facciate Vetrate — Fulgur Service',
    metaDescription: 'Pulizia professionale vetrate in altezza a Parma. Operatori certificati, funi e piattaforme omologate. Facciate, lucernari, finestre industriali.',
    image: '/images/servizi/pulizia-vetrate-altezza-parma.jpg',
  },
  {
    id: '09',
    slug: 'pannelli-fotovoltaici',
    title: 'Pulizia Pannelli Fotovoltaici',
    shortDesc: 'Pannelli sporchi = energia persa. Massimizza il rendimento del tuo impianto.',
    longDesc: 'I pannelli fotovoltaici sporchi perdono fino al 30% di efficienza. La nostra pulizia professionale rimuove polvere, pollini, depositi calcarei e guano senza danneggiare i pannelli, ripristinando la massima produzione energetica. Interventi periodici programmabili.',
    icon: 'Sun',
    featured: false,
    keywords: ['pulizia pannelli fotovoltaici Parma', 'lavaggio pannelli solari Parma', 'manutenzione fotovoltaico Parma'],
    benefits: ['Recupero fino al 30% di efficienza', 'Prodotti non abrasivi certificati', 'Acqua demineralizzata', 'Nessun danno ai pannelli', 'Interventi periodici programmati'],
    sectors: ['Impianti residenziali', 'Impianti industriali', 'Campi fotovoltaici', 'Capannoni produttivi'],
    metaTitle: 'Pulizia Pannelli Fotovoltaici Parma | Massima Efficienza — Fulgur Service',
    metaDescription: 'Pulizia professionale pannelli fotovoltaici a Parma. Recupera fino al 30% di efficienza. Prodotti non abrasivi, acqua demineralizzata. Preventivo gratuito.',
    image: '/images/servizi/pulizia-pannelli-fotovoltaici-parma.png',
  },
  {
    id: '10',
    slug: 'cantiere-navale',
    title: 'Cantiere Navale',
    shortDesc: 'Imbarcazioni, porti e environments marini: pulizia specializzata.',
    longDesc: 'Pulizia professionale per cantieri navali, imbarcazioni da diporto e ambienti portuali. Rimozione alghe, barnacle e depositi marini. Pulizia interni ed esterni barche, pontili e strutture portuali. Prodotti specifici per ambiente marino.',
    icon: 'Anchor',
    featured: false,
    keywords: ['pulizia cantiere navale', 'pulizia barche Parma', 'pulizia imbarcazioni'],
    benefits: ['Pulizia scafi e carene', 'Rimozione alghe e barnacle', 'Pulizia interni imbarcazioni', 'Strutture portuali', 'Prodotti eco per ambiente marino'],
    sectors: ['Cantieri navali', 'Porti turistici', 'Rimessaggi barche', 'Imbarcazioni da diporto'],
    metaTitle: 'Pulizia Cantiere Navale | Imbarcazioni e Porti — Fulgur Service',
    metaDescription: 'Pulizia professionale cantieri navali e imbarcazioni. Rimozione alghe, pulizia scafi, strutture portuali. Prodotti eco per ambiente marino.',
    image: '/images/servizi/pulizie-cantiere-navale-parma.jpg',
  },
  {
    id: '11',
    slug: 'sanificazione-vapore',
    title: 'Sanificazione Vapore 180°',
    shortDesc: 'Vapore saturo a 180°: igienizzazione profonda senza chimica aggressiva.',
    longDesc: 'La sanificazione con vapore saturo a 180° elimina il 99.9% di batteri, virus e acari senza utilizzare prodotti chimici aggressivi. Ideale per ambienti sensibili, famiglie con bambini, structures sanitarie e ovunque sia richiesta igienizzazione profonda e sicura.',
    icon: 'Wind',
    featured: false,
    keywords: ['sanificazione vapore Parma', 'igienizzazione vapore Parma', 'sanificazione naturale Parma'],
    benefits: ['Elimina 99.9% batteri e virus', 'Zero prodotti chimici aggressivi', 'Sicuro per bambini e allergici', 'Rimuove acari e allergeni', 'Igienizza tessuti e imbottiture'],
    sectors: ['Abitazioni con bambini/anziani', 'Strutture sanitarie', 'Asili e scuole', 'Alberghi', 'Ristoranti e cucine'],
    metaTitle: 'Sanificazione con Vapore 180° Parma | Igienizzazione Profonda — Fulgur Service',
    metaDescription: 'Sanificazione con vapore saturo a 180° a Parma. Elimina 99.9% di batteri e virus senza chimica aggressiva. Sicuro, efficace, eco-sostenibile.',
    image: '/images/fulgur-service-pulizie-sostenibili.jpg',
  },
  {
    id: '12',
    slug: 'pulizie-civili',
    title: 'Pulizie Civili',
    shortDesc: 'Abitazioni private, ville e appartamenti: la tua casa è in buone mani.',
    longDesc: 'Pulizie residenziali per abitazioni private di qualsiasi dimensione. Pulizie ordinarie periodiche o straordinarie di fondo. Prodotti delicati ma efficaci. Team discreto e di fiducia, puntuale e professionale. La tua casa trattata come se fosse la nostra.',
    icon: 'House',
    featured: false,
    keywords: ['pulizie civili Parma', 'pulizie casa Parma', 'pulizie appartamento Parma', 'pulizie villa Parma'],
    benefits: ['Pulizie ordinarie periodiche', 'Pulizie straordinarie di fondo', 'Prodotti delicati e certificati', 'Team discreto e di fiducia', 'Orari flessibili'],
    sectors: ['Appartamenti', 'Ville private', 'Abitazioni in affitto', 'Case vacanza'],
    metaTitle: 'Pulizie Civili Parma | Casa e Abitazioni Private — Fulgur Service',
    metaDescription: 'Pulizie civili professionali a Parma per appartamenti, ville e abitazioni private. Team discreto, prodotti delicati, puntualità garantita. Preventivo gratuito.',
    image: '/images/servizi/pulizie-civili-parma.jpg',
  },
]

// Servizi integrati — Impresa 360°
export const INTEGRATED_SERVICES = [
  {
    title: 'Manutenzione idraulica',
    desc: 'Interventi idraulici di manutenzione ordinaria inclusi per i clienti Fulgur',
    icon: 'Drop',
  },
  {
    title: 'Piccola manutenzione edile',
    desc: 'Riparazioni murarie, tinteggiature, piccoli lavori edili',
    icon: 'Wrench',
  },
  {
    title: 'Gestione rifiuti',
    desc: 'Esposizione e rientro contenitori secondo calendario comunale',
    icon: 'Recycle',
  },
  {
    title: 'Manutenzione elettrica',
    desc: 'Interventi di manutenzione elettrica ordinaria',
    icon: 'Lightning',
  },
]
