// lib/services-data.ts — Fulgur Service
// Copia esatta da GEMINI.md sezione 3

export interface Service {
  id: string
  slug: string
  title: string
  shortDesc: string
  longDesc: string
  icon: string  // nome icona @phosphor-icons
  featured: boolean
  keywords: string[]
  benefits: string[]
  sectors: string[]  // a chi è rivolto
  metaTitle: string
  metaDescription: string
  image: string
}

export const SERVICES: Service[] = [
  {
    id: '01',
    slug: 'pulizie-aziendali',
    title: 'Pulizie Aziendali',
    shortDesc: 'Servizi di pulizia professionale per uffici, negozi e spazi commerciali a Parma e provincia.',
    longDesc: 'Garantiamo ambienti di lavoro impeccabili. Gestiamo pulizie ordinarie e straordinarie per uffici, sedi aziendali, showroom e spazi commerciali a Parma di ogni dimensione. Team dedicato, prodotti eco-certificati e interventi su misura.',
    icon: 'Buildings',
    featured: true,
    keywords: ['pulizie uffici Parma', 'pulizie aziendali Parma', 'pulizie commerciali Parma', 'pulizia negozi Parma'],
    benefits: ['Pulizie uffici giornaliere e settimanali', 'Sanificazione postazioni e aree comuni', 'Pulizia vetrate e facciate commerciali', 'Utilizzo prodotti eco-sostenibili', 'Team qualificato e assicurato'],
    sectors: ['Uffici direzionali', 'Negozi e Showroom', 'Banche e Assicurazioni', 'Spazi Co-working'],
    metaTitle: 'Pulizie Uffici e Aziendali Parma | Fulgur Service',
    metaDescription: 'Pulizie professionali per uffici e aziende a Parma. Massima igiene, prodotti eco e preventivi rapidi. Scopri i nostri servizi aziendali.',
    image: '/images/servizi/pulizie-aziendali-parma.jpg',
  },
  {
    id: '02',
    slug: 'pulizie-industriali',
    title: 'Pulizie Industriali',
    shortDesc: 'Pulizia professionale di capannoni, magazzini e stabilimenti industriali a Parma.',
    longDesc: 'Interventi specializzati per ambienti complessi: capannoni, magazzini logistici e impianti produttivi. Utilizziamo macchinari industriali ad alte prestazioni per rimuovere residui ostinati e garantire la sicurezza degli ambienti di lavoro.',
    icon: 'Factory',
    featured: true,
    keywords: ['pulizie industriali Parma', 'pulizia capannoni Parma', 'pulizia magazzini Parma', 'pulizia stabilimenti Parma'],
    benefits: ['Trattamento pavimenti industriali', 'Rimozione oli, grassi e residui edili', 'Pulizia grandi vetrate industriali', 'Interventi rapidi a produzione ferma', 'Operatori formati alla sicurezza'],
    sectors: ['Capannoni e Magazzini', 'Officine Meccaniche', 'Stabilimenti Alimentari', 'Centri Logistici'],
    metaTitle: 'Pulizie Industriali e Capannoni Parma | Fulgur Service',
    metaDescription: 'Servizi di pulizia industriale a Parma per capannoni e magazzini. Macchinari professionali, team esperto e preventivi in 48 ore.',
    image: '/images/servizi/pulizie-industriali-parma.jpg',
  },
  {
    id: '03',
    slug: 'settore-sanitario',
    title: 'Settore Sanitario',
    shortDesc: 'Sanificazione certificata HACCP per cliniche, studi medici e farmacie a Parma.',
    longDesc: 'L’igiene clinica è la nostra specialità. Seguiamo protocolli certificati HACCP, utilizziamo presidi medico-chirurgici e prodotti virucidi approvati per garantire ambienti sicuri a pazienti e personale sanitario.',
    icon: 'FirstAidKit',
    featured: true,
    keywords: ['sanificazione Parma', 'pulizie studi medici Parma', 'pulizie cliniche Parma', 'HACCP Parma'],
    benefits: ['Protocolli di sanificazione certificati', 'Uso di prodotti virucidi e battericidi', 'Igienizzazione profonda sale d’attesa', 'Pulizia specialistica laboratori', 'Reportistica interventi documentata'],
    sectors: ['Studi Medici e Dentistici', 'Cliniche e Poliambulatori', 'Farmacie', 'Centri Estetici'],
    metaTitle: 'Sanificazione e Pulizie Sanitarie Parma | Fulgur Service',
    metaDescription: 'Servizi di sanificazione e pulizia per studi medici e cliniche a Parma. Protocolli HACCP e massima sicurezza igienica.',
    image: '/images/operatori-pulizie-professionali-parma.jpg',
  },
  {
    id: '04',
    slug: 'pulizie-condomini',
    title: 'Pulizie Condomini',
    shortDesc: 'Gestione completa pulizie scale, androni e aree comuni condominiali a Parma.',
    longDesc: 'Gestiamo la pulizia di tutte le parti comuni condominiali: scale, androni, ascensori, garage e aree esterne a Parma e provincia. Contratti trasparenti e rendicontazione digitale per gli amministratori.',
    icon: 'BuildingApartment',
    featured: false,
    keywords: ['pulizie condomini Parma', 'pulizia scale Parma', 'amministrazione condomini Parma'],
    benefits: ['Pulizia scale e androni programmata', 'Sanificazione ascensori e corrimano', 'Pulizia garage e aree cortilizie', 'Manutenzione aree verdi condominiali', 'Report mensile per amministratori'],
    sectors: ['Condomini residenziali', 'Complessi direzionali', 'Palazzi storici', 'Residence'],
    metaTitle: 'Pulizie Condomini e Scale Parma | Fulgur Service',
    metaDescription: 'Servizi di pulizia professionale per condomini a Parma. Affidabilità, trasparenza e cura delle aree comuni. Contattaci per un preventivo.',
    image: '/images/servizi/pulizie-condomini-parma.jpg',
  },
  {
    id: '05',
    slug: 'settore-alberghiero',
    title: 'Settore Alberghiero',
    shortDesc: 'Servizi di housekeeping e pulizia per hotel e B&B a Parma e provincia.',
    longDesc: 'Standard di pulizia elevati per il settore ricettivo. Gestiamo pulizia camere, lobby, spa e aree comuni con la massima discrezione, garantendo un’esperienza eccellente ai tuoi ospiti a Parma.',
    icon: 'Bed',
    featured: false,
    keywords: ['pulizie hotel Parma', 'housekeeping Parma', 'pulizie B&B Parma', 'pulizia strutture ricettive'],
    benefits: ['Gestione completa housekeeping camere', 'Pulizia profonda hall e aree comuni', 'Sanificazione spa e centri benessere', 'Lavaggio vetrate e facciate hotel', 'Personale formato e discreto'],
    sectors: ['Hotel e Alberghi', 'B&B e affittacamere', 'Agriturismi', 'Residence Turistici'],
    metaTitle: 'Pulizie Hotel e Settore Alberghiero Parma | Fulgur Service',
    metaDescription: 'Servizi professionali di pulizia e housekeeping per hotel e B&B a Parma. Esperienza e discrezione garantite.',
    image: '/images/servizi/pulizie-settore-alberghiero-hotel-bed-breakfast-parma.webp',
  },
  {
    id: '06',
    slug: 'trattamento-superfici',
    title: 'Trattamento Superfici',
    shortDesc: 'Lavaggio meccanizzato e trattamento di marmo, cotto, parquet e altre superfici a Parma.',
    longDesc: 'Proteggiamo e valorizziamo i tuoi pavimenti con tecniche avanzate. Da oltre 40 anni siamo specialisti nella cristallizzazione del marmo, trattamenti per gres porcellanato e oliatura parquet a Parma.',
    icon: 'Sparkle',
    featured: true,
    keywords: ['lucidatura marmo Parma', 'trattamento gres Parma', 'cristallizzazione marmo Parma', 'levigatura pavimenti'],
    benefits: ['Cristallizzazione professionale marmo', 'Trattamento antimacchia per gres', 'Oliatura e ripristino parquet', 'Pulizia profonda cotto e resina', 'Sistemi Klindex ad alta precisione'],
    sectors: ['Abitazioni private', 'Uffici di rappresentanza', 'Negozi e showroom', 'Hotel di lusso'],
    metaTitle: 'Trattamento Pavimenti e Lucidatura Marmo Parma | Fulgur Service',
    metaDescription: 'Esperti nel trattamento superfici a Parma: marmo, gres, parquet e cotto. Risultati duraturi con tecnologie all’avanguardia.',
    image: '/images/trattamento-superfici-parma.jpg',
  },
  {
    id: '07',
    slug: 'pulizie-fine-cantiere',
    title: 'Fine Cantiere',
    shortDesc: 'Pulizie post-ristrutturazione e fine cantiere a Parma per nuove costruzioni.',
    longDesc: 'Rendiamo il tuo spazio pronto alla consegna. Rimuoviamo residui calcarei, cementizi, vernici e polveri edili da nuove costruzioni e ristrutturazioni a Parma e provincia.',
    icon: 'HardHat',
    featured: false,
    keywords: ['pulizie fine cantiere Parma', 'pulizie post-ristrutturazione Parma', 'pulizia dopo lavori edili'],
    benefits: ['Rimozione calce e cemento', 'Pulizia vetri da residui di vernice', 'Aspirazione polveri edili sottili', 'Lucidatura pavimentazioni nuove', 'Sgombero e smaltimento residui'],
    sectors: ['Ristrutturazioni Private', 'Nuove costruzioni immobiliari', 'Uffici recentemente rinnovati'],
    metaTitle: 'Pulizie Fine Cantiere e Post-Ristrutturazione Parma | Fulgur Service',
    metaDescription: 'Servizi di pulizia post-cantiere a Parma. Rimozione residui edili e consegna locali impeccabili. Preventivi rapidi.',
    image: '/images/servizi/pulizie-fine-cantiere-parma.jpg',
  },
  {
    id: '08',
    slug: 'vetrate-altezza',
    title: 'Vetrate in Altezza',
    shortDesc: 'Pulizia professionale vetrate e facciate continue in altezza a Parma.',
    longDesc: 'Risultati brillanti in totale sicurezza. Il nostro personale certificato opera su piattaforme aeree e con sistemi a fune per la pulizia di vetrate, facciate ed edifici commerciali a Parma.',
    icon: 'ArrowsOutSimple',
    featured: false,
    keywords: ['pulizia vetrate Parma', 'lavaggio vetri altezza Parma', 'pulizia facciate Parma'],
    benefits: ['Operatori certificati per lavori in quota', 'Utilizzo di piattaforme aeree e funi', 'Pulizia facciate continue commerciali', 'Trattamento antioppacizzante vetri', 'Nessun limite di altezza'],
    sectors: ['Centri Direzionali', 'Palazzi Storici', 'Edifici Commerciali', 'Showroom'],
    metaTitle: 'Pulizia Vetrate e Facciate in Altezza Parma | Fulgur Service',
    metaDescription: 'Specialisti nella pulizia di vetrate in altezza a Parma. Sicurezza, professionalità e risultati impeccabili su ogni superficie vetrata.',
    image: '/images/servizi/pulizia-vetrate-altezza-parma.jpg',
  },
  {
    id: '09',
    slug: 'pannelli-fotovoltaici',
    title: 'Pulizia Pannelli Fotovoltaici',
    shortDesc: 'Manutenzione e pulizia pannelli fotovoltaici a Parma per massima efficienza.',
    longDesc: 'Recupera fino al 30% della produzione energetica. La nostra pulizia professionale a Parma utilizza acqua demineralizzata per rimuovere polvere e guano senza danneggiare i tuoi pannelli solari.',
    icon: 'Sun',
    featured: false,
    keywords: ['pulizia fotovoltaico Parma', 'lavaggio pannelli solari Parma', 'manutenzione fotovoltaico'],
    benefits: ['Aumento immediato efficienza energetica', 'Utilizzo acqua demineralizzata pura', 'Zero residui di calcare e aloni', 'Nessun utilizzo agenti abrasivi', 'Interventi sicuri per impianti civili e industriali'],
    sectors: ['Impianti Fotovoltaici Casa', 'Aziende con impianti solari', 'Campi fotovoltaici industriali'],
    metaTitle: 'Pulizia Pannelli Fotovoltaici e Solari Parma | Fulgur Service',
    metaDescription: 'Ottimizza la resa del tuo impianto fotovoltaico a Parma. Pulizia professionale con acqua demineralizzata. Preventivo gratuito.',
    image: '/images/servizi/pannelli-fotovoltaici-parma.jpg',
  },
  {
    id: '10',
    slug: 'cantiere-navale',
    title: 'Cantiere Navale',
    shortDesc: 'Imbarcazioni, porti e ambienti marini: pulizia specializzata.',
    longDesc: 'Pulizia professionale per cantieri navali, imbarcazioni da diporto e ambienti portuali. Rimozione alghe, barnacle e depositi marini. Pulizia interni ed esterni barche, pontili e strutture portuali. Prodotti specifici per ambiente marino.',
    icon: 'Anchor',
    featured: false,
    keywords: ['pulizia cantiere navale', 'pulizia barche Parma', 'pulizia imbarcazioni'],
    benefits: ['Pulizia scafi e carene', 'Rimozione alghe e barnacle', 'Pulizia interni imbarcazioni', 'Strutture portuali', 'Prodotti eco per ambiente marino'],
    sectors: ['Cantieri navali', 'Porti turistici', 'Rimessaggi barche', 'Imbarcazioni da diporto'],
    metaTitle: 'Pulizia Cantiere Navale | Imbarcazioni e Porti — Fulgur Service',
    metaDescription: 'Pulizia professionale cantieri navali e imbarcazioni. Rimozione alghe, pulizia scafi, strutture portuali. Prodotti eco per ambiente marino.',
    image: '/images/servizi/pulizie-cantiere-navale-parma.jpg',
  },
  {
    id: '11',
    slug: 'sanificazione-vapore',
    title: 'Sanificazione Vapore 180°',
    shortDesc: 'Igienizzazione profonda a vapore 180° a Parma: ecologica e senza chimica.',
    longDesc: 'Eliminiamo il 99.9% di virus e batteri in modo naturale. La nostra sanificazione a vapore saturo a 180° a Parma è ideale per ambienti con bambini, allergici o per chi cerca un’igiene totale senza residui chimici.',
    icon: 'Wind',
    featured: false,
    keywords: ['sanificazione vapore Parma', 'igienizzazione naturale Parma', 'pulizia vapore 180 gradi'],
    benefits: ['Eliminazione 99.9% batteri e acari', 'Trattamento 100% ecologico e sicuro', 'Igienizzazione tessuti e materassi', 'Zero residui chimici nocivi', 'Ideale per asili e studi medici'],
    sectors: ['Scuole e Asili', 'Abitazioni Private', 'Studi Medici', 'Settore Food'],
    metaTitle: 'Sanificazione a Vapore 180° Parma | Igiene Naturale | Fulgur Service',
    metaDescription: 'Sanificazione professionale a vapore 180° a Parma. Igienizzazione profonda, ecologica e sicura per ogni ambiente.',
    image: '/images/fulgur-service-pulizie-sostenibili.jpg',
  },
  {
    id: '12',
    slug: 'pulizie-civili',
    title: 'Pulizie Civili',
    shortDesc: 'Pulizia quotidiana e straordinaria per case, ville e appartamenti a Parma.',
    longDesc: 'Affidabilità e discrezione per la tua casa. Offriamo servizi di pulizia civile a Parma con personale selezionato, occupandoci dei tuoi spazi con la massima cura e attenzione ai dettagli.',
    icon: 'House',
    featured: false,
    keywords: ['pulizie casa Parma', 'pulizie appartamenti Parma', 'impresa pulizie casa Parma'],
    benefits: ['Personale di fiducia e assicurato', 'Pulizie di fondo e stagionali', 'Uso di prodotti delicati e sicuri', 'Massima flessibilità oraria', 'Discrezione e precisione garantite'],
    sectors: ['Ville e Appartamenti', 'Case in affitto / Airbnb', 'Abitazioni in fase di trasloco'],
    metaTitle: 'Pulizie Civili e Casa Parma | Fulgur Service',
    metaDescription: 'Servizi di pulizia per abitazioni private a Parma. Pulizie ordinarie e straordinarie con la qualità garantita di Fulgur Service.',
    image: '/images/servizi/pulizie-civili-parma.jpg',
  },
  {
    id: '13',
    slug: 'strutture-sportive',
    title: 'Strutture Sportive',
    shortDesc: 'Pulizia e sanificazione per palestre, piscine e centri sportivi a Parma.',
    longDesc: 'Garantiamo igiene totale in spogliatoi, docce, sale pesi e aree comuni. Utilizziamo prodotti specifici per eliminare batteri e funghi, assicurando un ambiente sano e sicuro per gli atleti e i frequentatori della struttura.',
    icon: 'Trophy',
    featured: false,
    keywords: ['pulizie palestre Parma', 'sanificazione centri sportivi', 'pulizia piscine Parma'],
    benefits: ['Igienizzazione profonda spogliatoi e docce', 'Sanificazione attrezzature sportive', 'Trattamento antiscivolo bordovasca', 'Prodotti antifungini e antibatterici', 'Interventi in orari di chiusura'],
    sectors: ['Palestre e Fitness Club', 'Piscine', 'Palazzetti dello Sport', 'Centri Padel e Tennis'],
    metaTitle: 'Pulizia Strutture Sportive e Palestre Parma | Fulgur Service',
    metaDescription: 'Sanificazione e pulizia professionale per palestre, piscine e centri sportivi a Parma. Igiene totale e sicurezza per gli atleti.',
    image: '/images/servizi/pulizie-palestre-strutture-sportive-parma.jpg',
  },
  {
    id: '14',
    slug: 'locali-notturni',
    title: 'Locali Notturni',
    shortDesc: 'Interventi rapidi ed efficaci per discoteche, pub e locali serali a Parma.',
    longDesc: 'Riportiamo all\'ordine discoteche e locali notturni prima della successiva apertura. Rimuoviamo macchie ostinate, puliamo vetrate, pavimenti e servizi igienici con squadre rapide che operano nelle prime ore del mattino.',
    icon: 'Martini',
    featured: false,
    keywords: ['pulizie discoteche Parma', 'pulizie pub Parma', 'pulizie locali notturni'],
    benefits: ['Interventi rapidi post-chiusura', 'Lavaggio meccanizzato pavimenti', 'Sanificazione intensiva bagni', 'Rimozione macchie su arredi e tessuti', 'Smaltimento vetro e rifiuti'],
    sectors: ['Discoteche', 'Pub e Birrerie', 'Lounge Bar', 'Sale Concerti'],
    metaTitle: 'Pulizie Locali Notturni e Discoteche Parma | Fulgur Service',
    metaDescription: 'Servizi di pulizia rapida post-serata per discoteche e pub a Parma. Ripristino totale dell\'igiene prima della riapertura.',
    image: '/images/servizi/pulizie-locali-notturni-parma.webp',
  },
  {
    id: '15',
    slug: 'pulizia-facciate',
    title: 'Pulizia Facciate',
    shortDesc: 'Lavaggio e ripristino di facciate esterne civili e industriali a Parma.',
    longDesc: 'Restituiamo decoro agli edifici rimuovendo smog, muschio, graffiti e segni del tempo. Interveniamo su facciate in mattoni, pietra, intonaco e rivestimenti moderni con tecniche ad alta pressione, sabbiatura leggera o macchinari a osmosi.',
    icon: 'Buildings', 
    featured: false,
    keywords: ['pulizia facciate Parma', 'lavaggio muri esterni Parma', 'rimozione graffiti Parma'],
    benefits: ['Idrolavaggio a pressione controllata', 'Rimozione smog e agenti inquinanti', 'Sistemi ad osmosi per rivestimenti', 'Trattamenti idrorepellenti protettivi', 'Sverniciatura e rimozione graffiti'],
    sectors: ['Case e Condomini', 'Capannoni Industriali', 'Edifici Storici', 'Centri Commerciali'],
    metaTitle: 'Pulizia Facciate e Lavaggio Esterni Parma | Fulgur Service',
    metaDescription: 'Servizi di lavaggio facciate esterne a Parma. Rimozione di smog, muschio e graffiti per ripristinare il decoro del tuo edificio.',
    image: '/images/servizi/pulizia-facciate-parma.jpg',
  },
]

// Servizi integrati — Impresa 360°
export const INTEGRATED_SERVICES = [
  {
    title: 'Manutenzione idraulica',
    desc: 'Interventi idraulici di manutenzione ordinaria inclusi per i clienti Fulgur',
    icon: 'Drop',
  },
  {
    title: 'Piccola manutenzione edile',
    desc: 'Riparazioni murarie, tinteggiature, piccoli lavori edili',
    icon: 'Wrench',
  },
  {
    title: 'Gestione rifiuti',
    desc: 'Esposizione e rientro contenitori secondo calendario comunale',
    icon: 'Recycle',
  },
  {
    title: 'Manutenzione elettrica',
    desc: 'Interventi di manutenzione elettrica ordinaria',
    icon: 'Lightning',
  },
  {
    title: 'Manutenzione giardinaggio',
    desc: 'Cura di aree verdi, potature e manutenzione ordinaria del verde',
    icon: 'Leaf',
  },
]
