export interface Town {
  slug: string
  name: string
  title: string
  heroTitle: string
  heroSub: string
  description: string
  metaTitle: string
  metaDescription: string
  keySector: string
  keyBenefit: string
}

export const TOWNS: Town[] = [
  {
    slug: 'parma',
    name: 'Parma',
    title: 'Impresa di Pulizie Parma',
    heroTitle: 'Il Riferimento per le Pulizie a Parma',
    heroSub: 'Dalla zona SPIP al centro storico: pulizie professionali per aziende, condomini e privati.',
    description: 'Fulgur Service ha sede a Parma e conosce il territorio meglio di qualsiasi altra impresa di pulizie. Interveniamo quotidianamente in tutti i quartieri della città: centro storico, Oltretorrente, Montanara, San Lazzaro, zona industriale SPIP. Sopralluogo gratuito entro 24 ore, preventivo fisso senza sorprese.',
    metaTitle: 'Impresa di Pulizie Parma | Preventivo in 24h | Fulgur Service',
    metaDescription: 'Fulgur Service è l\'impresa di pulizie con sede a Parma. Uffici, condomini, capannoni e abitazioni. Sopralluogo gratuito in 24h. Personale assicurato e referente unico.',
    keySector: 'Tutti i settori Sede Operativa',
    keyBenefit: 'Sopralluogo in 24h',
  },
  {
    slug: 'fidenza',
    name: 'Fidenza',
    title: 'Pulizie Professionali Fidenza',
    heroTitle: 'Eccellenza nel Cleaning a Fidenza',
    heroSub: 'Servizi specializzati per uffici, negozi e il polo commerciale di Fidenza.',
    description: 'Fulgur Service opera a Fidenza offrendo soluzioni di pulizia certificate per il settore commerciale e terziario. La nostra vicinanza ci permette interventi rapidi e sopralluoghi gratuiti in 48 ore. Serviamo regolarmente le strutture commerciali vicino a Fidenza Village e le aziende del polo produttivo locale.',
    metaTitle: 'Impresa di Pulizie Fidenza | Uffici e Negozi | Fulgur Service',
    metaDescription: 'Cerchi un\'impresa di pulizie a Fidenza? Fulgur Service offre pulizie professionali per uffici, negozi e condomini a Fidenza. Sopralluogo gratuito in 48h.',
    keySector: 'Settore Commerciale & Outlet',
    keyBenefit: 'Pronto Intervento 48h',
  },
  {
    slug: 'salsomaggiore-terme',
    name: 'Salsomaggiore Terme',
    title: 'Pulizie Salsomaggiore Terme',
    heroTitle: 'Igiene Superiore a Salsomaggiore',
    heroSub: 'Protocolli sanitari e alberghieri per la città termale.',
    description: 'Sosteniamo il prestigio di Salsomaggiore Terme con servizi di pulizia per hotel, spa e strutture sanitarie. Operiamo con tecnologie a vapore 180° e prodotti eco-certificati. Il settore alberghiero termale richiede standard elevati: conosciamo le esigenze specifiche di queste strutture e organizziamo interventi programmati nei periodi di minore occupazione.',
    metaTitle: 'Impresa di Pulizie Salsomaggiore Terme | Hotel e Spa | Fulgur Service',
    metaDescription: 'Servizi professionali di pulizia e sanificazione a Salsomaggiore Terme. Specializzati nel settore alberghiero e sanitario. Richiedi preventivo.',
    keySector: 'Alberghiero & Benessere',
    keyBenefit: 'Sanificazione Certificata',
  },
  {
    slug: 'collecchio',
    name: 'Collecchio',
    title: 'Pulizie Industriali Collecchio',
    heroTitle: 'Partner Tecnico a Collecchio',
    heroSub: 'Pulizie industriali e manutenzioni per il polo produttivo di Collecchio.',
    description: 'A Collecchio siamo il punto di riferimento per le industrie alimentari e meccaniche della zona. Garantiamo standard HACCP e macchinari di ultima generazione per grandi superfici. Il polo produttivo di Collecchio ospita aziende dell\'eccellenza alimentare italiana: conosciamo le loro esigenze e operiamo con protocolli specifici per ogni tipologia di stabilimento.',
    metaTitle: 'Impresa di Pulizie Collecchio | Industriale e Civile | Fulgur Service',
    metaDescription: 'Pulizie professionali a Collecchio per aziende e privati. Specialisti in pulizie industriali e manutenzioni integrate. Contattaci ora.',
    keySector: 'Industria Alimentare & Logistica',
    keyBenefit: 'Protocolli HACCP',
  },
  {
    slug: 'langhirano',
    name: 'Langhirano',
    title: 'Pulizie Industriali Langhirano',
    heroTitle: 'Igiene Industriale a Langhirano',
    heroSub: 'Sanificazione certificata per prosciuttifici e industrie alimentari DOP.',
    description: 'Langhirano è la capitale mondiale del Prosciutto di Parma: ogni stabilimento deve rispettare protocolli igienici rigidissimi per mantenere la certificazione DOP. Fulgur Service interviene con protocolli HACCP specifici per ambienti di stagionatura, celle frigorifere e linee di lavorazione, garantendo la massima igiene senza interferire con il processo produttivo.',
    metaTitle: 'Pulizie Industriali Langhirano | Prosciuttifici e Settore DOP | Fulgur Service',
    metaDescription: 'Sanificazione certificata HACCP per prosciuttifici e stabilimenti alimentari a Langhirano. Protocolli DOP, celle frigorifere, linee produttive. Preventivo gratuito.',
    keySector: 'Industria Alimentare DOP',
    keyBenefit: 'Certificazione HACCP DOP',
  },
  {
    slug: 'noceto',
    name: 'Noceto',
    title: 'Pulizie Professionali Noceto',
    heroTitle: 'Servizi di Pulizia a Noceto',
    heroSub: 'Pulizie industriali e civili per aziende e privati di Noceto e dintorni.',
    description: 'Operiamo a Noceto e nelle frazioni limitrofe con servizi di pulizia per il settore produttivo locale, condomini e abitazioni private. La nostra posizione logistica ci permette tempi di intervento ridotti per tutta la zona tra Parma e Noceto.',
    metaTitle: 'Impresa di Pulizie Noceto | Industriale e Civile | Fulgur Service',
    metaDescription: 'Pulizie professionali a Noceto per aziende, condomini e privati. Interventi rapidi e sopralluogo gratuito. Contatta Fulgur Service di Parma.',
    keySector: 'Industria & Civile',
    keyBenefit: 'Interventi Rapidi',
  },
  {
    slug: 'fontevivo',
    name: 'Fontevivo',
    title: 'Pulizie e Logistica Fontevivo',
    heroTitle: 'Cleaning Professionale nell\'Interporto di Fontevivo',
    heroSub: 'Pulizie per magazzini logistici, hub di distribuzione e capannoni nell\'area interportuale.',
    description: 'L\'interporto di Fontevivo è uno dei principali hub logistici dell\'Emilia-Romagna. Fulgur Service è presente nell\'area con servizi di pulizia meccanizzata per grandi superfici: lavasciuga uomo a bordo, rimozione oli e polveri, report per audit logistici. Interventi pianificati nei turni notturni o nel fine settimana.',
    metaTitle: 'Pulizie Magazzini Fontevivo | Interporto e Logistica | Fulgur Service',
    metaDescription: 'Pulizia professionale per magazzini logistici e capannoni nell\'area interportuale di Fontevivo. Lavasciuga industriale, interventi notturni. Preventivo gratuito.',
    keySector: 'Logistica & Distribuzione',
    keyBenefit: 'Lavasciuga Industriale',
  },
  {
    slug: 'traversetolo',
    name: 'Traversetolo',
    title: 'Pulizie Professionali Traversetolo',
    heroTitle: 'Pulizie nell\'Appennino Parmense',
    heroSub: 'Servizi di pulizia per abitazioni, aziende e strutture nella zona collinare di Parma.',
    description: 'Operiamo a Traversetolo e nei comuni della collina parmense offrendo pulizie civili per ville e abitazioni di pregio, pulizie industriali per le aziende della zona e trattamento di superfici pregiate come marmo e cotto tipici delle dimore collinari.',
    metaTitle: 'Impresa di Pulizie Traversetolo | Collina Parmense | Fulgur Service',
    metaDescription: 'Pulizie professionali a Traversetolo per abitazioni, ville e aziende della collina parmense. Trattamento marmo e cotto. Sopralluogo gratuito.',
    keySector: 'Civile & Residenziale',
    keyBenefit: 'Trattamento Superfici Pregiate',
  },
  {
    slug: 'colorno',
    name: 'Colorno',
    title: 'Pulizie Professionali Colorno',
    heroTitle: 'Cleaning Professionale a Colorno',
    heroSub: 'Pulizie per aziende agro-alimentari, strutture pubbliche e condomini di Colorno.',
    description: 'Colorno e la bassa parmense sono un territorio a forte vocazione agro-alimentare. Fulgur Service offre servizi di pulizia e sanificazione HACCP per aziende del settore alimentare, condomini e strutture pubbliche. Operiamo anche nelle aree limitrofe della bassa padana parmense.',
    metaTitle: 'Impresa di Pulizie Colorno | Bassa Parmense | Fulgur Service',
    metaDescription: 'Pulizie professionali a Colorno per industrie alimentari, condomini e strutture pubbliche. Sanificazione HACCP. Sopralluogo gratuito da Parma.',
    keySector: 'Agro-Alimentare & Civile',
    keyBenefit: 'Sanificazione HACCP',
  },
  {
    slug: 'sorbolo',
    name: 'Sorbolo',
    title: 'Pulizie Sorbolo e Mezzani',
    heroTitle: 'Pulizie Professionali a Sorbolo',
    heroSub: 'Servizi di pulizia per aziende, capannoni e abitazioni di Sorbolo e Mezzani.',
    description: 'Operiamo a Sorbolo e nel comune di Mezzani con pulizie industriali per il polo produttivo locale e servizi civili per abitazioni e condomini. La bassa parmense è un\'area in crescita produttiva: siamo disponibili per sopralluoghi gratuiti entro 48 ore dalla chiamata.',
    metaTitle: 'Impresa di Pulizie Sorbolo Mezzani | Industriale e Civile | Fulgur Service',
    metaDescription: 'Pulizie professionali a Sorbolo e Mezzani. Pulizie industriali, civili e condomini. Sopralluogo gratuito in 48h. Fulgur Service di Parma.',
    keySector: 'Industriale & Civile',
    keyBenefit: 'Intervento in 48h',
  },
]
